// qiankun_micro/qiankun-micro-app2/src/App.vue
<template>
  <div id="app">
    <h2>vue2 子应用</h2>
    <div class="menu">
      <router-link to="/">list</router-link>
      <router-link to="/detail">detail</router-link>
      <button @click="gotoVue3">vue3页面</button>
    </div>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "App",
  methods: {
    gotoVue3() {
      window.history.pushState({}, "", "/micro-vue3");
    },
  },
};
</script>

<style>
#app {
  width: 100%;
  height: 100%;
  margin: 0 auto;
  padding: 24px;
}
h2 {
  color: #333;
}

.menu {
  margin-top: 20px;
}

.menu a,
.menu button {
  margin-right: 10px;
  padding: 8px 12px;
  font-size: 16px;
  text-decoration: none;
  cursor: pointer;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 4px;
  transition: background-color 0.3s ease;
}

.menu a:hover,
.menu button:hover {
  background-color: #0056b3;
}
</style>

// qiankun_micro/qiankun-micro-app1/src/App.tsx
import './App.css';
import { Link, Routes, Route } from 'react-router-dom';
import List from './pages/List';
import Detail from './pages/Detail';

function App() {

  const goVue2 = () => {
    window.history.pushState({}, '', '/micro-vue2')
  }

  return (
    <div className="App">
      <h2>react 子应用</h2>
      <div className='menu'>
        <Link to={'/'}>list</Link>
        <Link to={'/detail'}>detail</Link>
        <button onClick={goVue2}>vue2页面</button>
      </div>
      <Routes>
        <Route path='/' element={<List />} />
        <Route path='/detail' element={<Detail />} />
      </Routes>
    </div>
  );
}

export default App;
